return{
	modinfo = "This mod file contains the base game data!",
	
	enemies = {
		pissecguard = {
			char="S",
			color={0,0.6,0.9,1},
			health=25,
			atksound="pistol",
			dice=3,
			sides=4,
			tohit=0.9,
			shots=1,
			xp=10,
			movetime=12,
			cooldown=1,
			aggro=0.8,
			range=9,
			name="Security Guard",
			desc="Simple security guard. Unarmored, lightly armed, and fortunately quite dumb.",
			deathmsg="The Security Guard collapses.",
			ammo="9mm",ammocount=12,drops={"m99pis","m99pis","secarm"}
		},
		shotsecguard = {
			char="S",
			color={0,0.6,0.9,1},
			health=25,
			atksound="shotgun",
			dice=3,
			sides=4,
			tohit=0.65,
			shots=3,
			xp=14,
			movetime=12,
			cooldown=2,
			aggro=0.8,
			range=8,
			name="Security Guard",
			desc="Simple security guard. Unarmored, lightly armed, and fortunately quite dumb.",
			deathmsg="The Security Guard collapses.",
			ammo="12ga",ammocount=4,drops={"sawnoff","sawnoff","secarm"}
		},
		secdog = {
			char="s",
			color={0,0.6,0.9,1},
			health=10,
			dice=4,
			sides=4,
			tohit=0.8,
			shots=1,
			xp=14,
			movetime=6,
			cooldown=2,
			aggro=1,
			range=1,
			name="Security Dog",
			desc="Aww, a doggy! Too bad it'll maul you to death if you let it. Sorry boy, you gotta go.",
			deathmsg="The Security Dog falls to its side."
		},
		smgtacguard = {
			char="R",
			color={0.6,0.6,0.6,1},
			health=50,
			atksound="submachine",
			dice=3,
			sides=4,
			tohit=0.6,
			shots=3,
			xp=24,
			movetime=11,
			cooldown=1,
			aggro=0.75,
			range=10,
			name="Riot Guard",
			desc="A riot guard, in riot guard armor. Wields some decent weaponry. Kill him and take it.",
			deathmsg="The Riot Guard drops to the ground.",
			ammo="9mm",ammocount=30,drops={"sm40smg","sm40smg","riotarm","secarm"}
		},
		rifletacguard = {
			char="R",
			color={0.6,0.6,0.6,1},
			health=50,
			atksound="rifle",
			dice=5,
			sides=4,
			tohit=0.8,
			shots=1,
			xp=27,
			movetime=11,
			cooldown=1,
			aggro=0.65,
			range=10,
			name="Riot Guard",
			desc="A riot guard, in riot guard armor. Wields some decent weaponry. Kill him and take it.",
			deathmsg="The Riot Guard drops to the ground.",
			ammo="5mm",ammocount=15,drops={"sn730rifle","riotarm","secarm"}
		},
		riflemilguard = {
			char="M",
			color={0,0.5,0,1},
			health=90,
			atksound="rifle",
			dice=5,
			sides=4,
			tohit=0.9,
			shots=2,
			xp=47,
			movetime=9,
			cooldown=1,
			aggro=0.8,
			range=10,
			name="Militia Guard",
			desc="This highly trained soldier will gladly show you to your grave. Armored, armed, and scary. Kill on sight.",
			deathmsg="The Militia Guard hits the floor.",
			ammo="5mm",ammocount=17,drops={"sn730rifle","sn730rifle","milarm","riotarm"}
		},
		shotmilguard = {
			char="M",
			color={0,0.5,0,1},
			health=90,
			atksound="shotgun",
			dice=4,
			sides=4,
			tohit=0.85,
			shots=3,
			xp=54,
			movetime=9,
			cooldown=2,
			aggro=0.7,
			range=9,
			name="Militia Guard",
			desc="This highly trained soldier will gladly show you to your grave. Armored, armed, and scary. Kill on sight.",
			deathmsg="The Militia Guard hits the floor.",
			ammo="12ga",ammocount=6,drops={"ca12shotty","ca12shotty","milarm","riotarm"}
		},
		mildog = {
			char="m",
			color={0,0.5,0,1},
			health=40,
			dice=5,
			sides=5,
			tohit=0.9,
			shots=1,
			xp=30,
			movetime=5,
			cooldown=2,
			aggro=1,
			range=1,
			name="Militia Dog",
			desc="Puppy! Yeah, no. Better get to firing, cos you're not outrunning this pupper.",
			deathmsg="The Militia Dog falls with a yelp."
		},
		gundrone = {
			char="D",
			color={0.4,0.4,0.4,1},
			health=50,
			atksound="rifle",
			dice=4,
			sides=5,
			tohit=0.8,
			shots=3,
			xp=40,
			movetime=5,
			cooldown=1,
			aggro=0.85,
			range=8,
			fly=true,
			name="Gun Drone",
			desc="Uh uh. Bad news. You need to take care of this thing before it takes care of you.",
			deathmsg="The Gun Drone hits the ground with a satisfying crack."
		},
		shockdrone = {
			char="d",
			color={0.4,0.4,0.4,1},
			health=50,
			dice=6,
			sides=4,
			tohit=1.0,
			shots=1,
			xp=35,
			movetime=5,
			cooldown=0,
			aggro=0.8,
			range=1.4,
			fly=true,
			name="Shock Drone",
			desc="It's fast, armored, and it has a taser. It's a taser attack drone. Who came up with this?",
			deathmsg="The Shock Drone falls from the sky, still buzzing its taser."
		},
		gundronesmall = {
			char="D",
			color={0.7,0.7,0.7,1},
			health=15,
			atksound="sm41",
			dice=3,
			sides=4,
			tohit=0.8,
			shots=2,
			xp=26,
			movetime=5,
			cooldown=1,
			aggro=0.85,
			range=6,
			fly=true,
			name="Lt.Gun Drone",
			desc="Hear the whirring. Hear the swarm.",
			deathmsg="The Drone falls."
		},
		shockdronesmall = {
			char="d",
			color={0.7,0.7,0.7,1},
			health=15,
			dice=6,
			sides=4,
			tohit=1.0,
			shots=1,
			xp=21,
			movetime=5,
			cooldown=0,
			aggro=0.7,
			range=1.3,
			fly=true,
			name="Lt.Shock Drone",
			desc="Hear the zapping. Hear the swarm.",
			deathmsg="The Drone falls."
		},
		turret1 = {
			char="t",
			color={0.4,0.4,0.4,1},
			health=70,
			atksound="submachine",
			dice=3,
			sides=4,
			tohit=0.7,
			shots=3,
			xp=30,
			movetime=18,
			cooldown=0,
			aggro=0.8,
			range=11,
			fly=true,
			name="Defense Turret",
			desc="Static ceiling mounted turret with a submachinegun.",
			deathmsg="The turret stops tracking.",
			ammo="9mm",ammocount=20,
			nomoving = true
		},
		turret2 = {
			char="T",
			color={0.4,0.4,0.4,1},
			health=100,
			atksound="rifle",
			dice=5,
			sides=4,
			tohit=0.8,
			shots=2,
			xp=40,
			movetime=16,
			cooldown=0,
			aggro=0.8,
			range=11,
			fly=true,
			name="Defense Turret",
			desc="Static ceiling mounted turret with a rifle.",
			deathmsg="The turret stops tracking.",
			ammo="5mm",ammocount=15,
			nomoving = true
		},
		protogunbot = {
			char="B",
			color={0.4,0.5,0.8,1},
			health=140,
			atksound="submachine",
			dice=3,
			sides=4,
			tohit=0.85,
			shots=3,
			xp=150,
			movetime=9,
			cooldown=0,
			aggro=0.75,
			range=9,
			name="Defense Bot",
			desc="It appears to be a quadrupedal robot with a submachinegun bolted to it. It isn't running out of ammo any time soon either.",
			deathmsg="The Defense Bot is destroyed! I hope to never see another."
		},
		gunbot = {
			char="B",
			color={0.5,1,0.6,1},
			atksound="rifle",
			health=200,
			dice=5,
			sides=5,
			tohit=0.9,
			shots=3,
			xp=300,
			movetime=9,
			cooldown=0,
			aggro=0.65,
			range=10,
			name="Defense Bot",
			desc="I guess the last one was a prototype. This one has a rifle instead of a submachinegun! Frabjous day.",
			deathmsg="The Defense Bot falls! That better be the last one."
		},
		eliteguard = {
			char="E",
			color={1,1,1,1},
			health=180,
			atksound="rifle",
			dice=5,
			sides=5,
			tohit=1.1,
			shots=2,
			xp=71,
			movetime=7,
			cooldown=1,
			aggro=0.7,
			range=11,
			name="Elite Guard",
			desc="These guys are guarding the deep research facility. Unfortunate.",
			deathmsg="The Elite Guard breaths its last breath.",
			ammo="5mm",ammocount=22,drops={"sn730rifle","sn730rifle","milarm","milarm","balarm"}
		}
	},
	
	items = {
		m99pis = {
			type="weapon",
			name="m99 Pistol",
			dice=4,
			sides=3,
			maxammo=12,
			ammotype="9mm",
			atktime=9,
			reltime=18,
			tohit=0.9,
			sound="pistol",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="An old but very popular handgun. Accurate and reliable. It'll do the trick for now.",
			char="}",
			color={0.5,0.5,0.5,1}
		},
		baton = {
			type="weapon",
			name="Baton",
			dice=2,
			sides=3,
			chrgtime=0,
			chrgbonus={1,4,7},
			charge=4,
			ammotype="no",
			atktime=12,
			tohit=0.8,
			sound="melee",
			dmgtype="melee",
			weaptype="small",
			desc="It's just a baton. Pretty simple and reliable.",
			char="/",
			color={0.4,0.4,0.5,1}
		},
		knife = {
			type="weapon",
			name="Combat Knife",
			dice=4,
			sides=2,
			chrgtime=-2,
			chrgbonus={1,1,2},
			charge=2,
			ammotype="no",
			atktime=9,
			tohit=0.85,
			sound="melee",
			dmgtype="melee",
			weaptype="small",
			desc="Blades have been around for centuries, but this one's mine.",
			char="/",
			color={0.6,0.6,0.7,1}
		},
		sawnoff = {
			type="weapon",
			name="Sawnoff Shotgun",
			dice=2,
			sides=4,
			maxammo=2,
			ammotype="12ga",
			atktime=3,
			reltime=14,
			tohit=0.7,
			range=4,
			sound="shotgun",
			dmgtype="spread",
			weaptype="sidearm",
			desc="A sawed-off double barreled shotgun. Very cheap, but rather ineffective.",
			char="}",
			color={0.7,0.5,0.45,1}
		},
		sm40smg = {
			type="weapon",
			name="sm-40 SMG",
			dice=3,
			sides=4,
			maxammo=30,
			ammotype="9mm",
			atktime=3.5,
			reltime=24,
			tohit=0.715,
			sound="submachine",
			dmgtype="bullet",
			weaptype="rapid",
			desc="The sm-40 fell out of style some time ago, mainly due to reliability issues. However, it's still a good gun in close range.",
			char="}",
			color={0.65,0.65,0.7,1}
		},
		ca12shotty = {
			type="weapon",
			name="CA12 Shotgun",
			dice=3,
			sides=4,
			maxammo=6,
			ammotype="12ga",
			atktime=10,
			reltime=25,
			tohit=0.75,
			range=7,
			sound="shotgun",
			dmgtype="spread",
			weaptype="shotgun",
			pickupmsg="Groovy.",
			desc="Ah, the beloved CA12 \"Whiplash\" pump-action shotgun. Groovy.",
			char="}",
			color={0.9,0.5,0.5,1}
		},
		ch7pis = {
			type="weapon",
			name="CH7 Pistol",
			dice=5,
			sides=4,
			maxammo=15,
			ammotype="9mm",
			atktime=9,
			reltime=18,
			tohit=0.9,
			sound="pistol",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="The CH7 Handgun is a very popular military service pistol, and with good reason.",
			char="}",
			color={0.5,0.7,0.6,1}
		},
		machete = {
			type="weapon",
			name="Machete",
			dice=4,
			sides=4,
			chrgtime=1,
			chrgbonus={3,5,7},
			charge=4,
			ammotype="no",
			atktime=11,
			tohit=0.6,
			sound="melee",
			dmgtype="melee",
			weaptype="medium",
			desc="The bigger blade. Excellent.",
			char="/",
			color={0.7,0.5,0.5,1}
		},
		knuckles = {
			type="weapon",
			name="Knuckleduster",
			dice=4,
			sides=3,
			chrgtime=-1,
			chrgbonus={2,4,8},
			charge=5,
			ammotype="no",
			atktime=11,
			tohit=0.6,
			sound="melee",
			dmgtype="melee",
			weaptype="medium",
			desc="A versatile melee weapon regulated in some places for its brutality. This one may be blunt, but do not underestimate it.",
			char="/",
			color={0.6,0.6,0.2,1}
		},
		sn730rifle = {
			type="weapon",
			name="SN730 Rifle",
			dice=5,
			sides=6,
			maxammo=30,
			ammotype="5mm",
			atktime=4,
			reltime=29,
			tohit=0.633,
			sound="rifle",
			dmgtype="bullet",
			weaptype="rapid",
			desc="Truly the bread and butter of any military operation.",
			char="}",
			color={0.4,0.4,0.8,1}
		},
		z3rifle = {
			type="weapon",
			name="z-3 Battlerifle",
			dice=7,
			sides=6,
			maxammo=20,
			ammotype="7mm",
			atktime=6,
			reltime=31,
			tohit=0.6,
			sound="batrifle",
			dmgtype="bullet",
			weaptype="rapid",
			pickupmsg="Hell yea.",
			desc="Firing scarily heavy bullets, the z-3 battle rifle is just what you need to go toe to toe with the biggest baddies out there.",
			char="}",
			color={0.9,0.8,0.5,1}
		},
		
		sword = {
			type="weapon",
			name="Arc Blade",
			dice=5,
			sides=4,
			chrgtime=0,
			chrgbonus={1,1,2},
			charge=1,
			ammotype="no",
			atktime=13,
			tohit=0.8,
			sound="pistol",
			dmgtype="melee",
			weaptype="medium",
			pickupmsg="Bzzzt.",
			desc="It resembles a machete, with a metal \"blade\" that lights up brightly along the edge and makes a horrid sound when you press the button in the grip.",
			char="/",
			color={0.7,0.3,1.0,1}
		},
		
		--new guns
		witchmag = {
			type="weapon",
			name="Magnum Revolver",
			dice=6,
			sides=3,
			maxammo=6,
			ammotype=".35",
			atktime=10,
			reltime=24,
			tohit=0.8,
			sound="magnum",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="What an ancient firearm. Kicks like a mule, pretty reliably.",
			char="}",
			color={0.4,0.65,0.5,1}
		},
		mk23pis = {
			type="weapon",
			name="mk21 Handcannon",
			dice=3,
			sides=5,
			maxammo=9,
			ammotype=".35",
			atktime=9,
			reltime=18,
			tohit=0.7,
			sound="magnum",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="This magnum pistol packs a lovely kick in an almost manageable package. Sadly not the most reliable, as the cartridge is a bit to hefty for the gun.",
			char="}",
			color={0.1,0.55,0.15,1}
		},
		huntrifle = {
			type="weapon",
			name="Hunting Rifle",
			dice=7,
			sides=4,
			maxammo=10,
			ammotype=".35",
			atktime=10,
			reltime=28,
			tohit=0.9,
			sound="batrifle",
			dmgtype="bullet",
			weaptype="shotgun",
			desc="Nice. Make sure to do a spin with it when you work the lever.",
			char="}",
			color={0.2,0.6,0.6,1}
		},
		bossrifle = {
			type="weapon",
			name="BM9 Rifle",
			dice=8,
			sides=7,
			maxammo=8,
			ammotype="7mm",
			atktime=13,
			reltime=20,
			tohit=0.8,
			sound="batrifle",
			dmgtype="bullet",
			weaptype="shotgun",
			desc="What a reputation the BM9 Sniper Rifle has. So long as you keep it clean, you can avoid that reputation! It's excellent at delivering pinpoint Fuck You at whatever it's pointed at.",
			char="}",
			color={0.2,0.6,0.6,1}
		},
		autopis = {
			type="weapon",
			name="sm-41 Micro-SMG",
			dice=2,
			sides=3,
			maxammo=20,
			ammotype="9mm",
			atktime=4,
			ammouse=2,
			shots=2,
			reltime=20,
			tohit=0.533,
			sound="sm41",
			dmgtype="bullet",
			weaptype="rapid",
			desc="What an odd little piece of junk. This crunched down version of the much better sm-40 is just downright uncontrollable. Fires too fast, if you can believe it.",
			char="}",
			color={0.3,0.3,0.45,1}
		},
		
		--new superweapons
		--these are conventional firearms that are very rare and expensive but very effective if you find one
		magsmg = {
			type="weapon",
			name="mk13 SMG",
			dice=5,
			sides=5,
			maxammo=22,
			ammotype=".35",
			atktime=3.5,
			reltime=24,
			tohit=0.7,
			sound="magnum",
			dmgtype="bullet",
			weaptype="rapid",
			pickupmsg="What a relic.",
			desc="The mk13 is a legendary submachinegun chambered in .35 magnum. Sadly it's not still in production, but if you can get your hands on one, it's very easy to use and very powerful.",
			char="}",
			color={0.8,0.75,0.15,1}
		},
		machinegun = {
			type="weapon",
			name="Machinegun",
			dice=6,
			sides=6,
			maxammo=50,
			ammotype="7mm",
			atktime=5,
			ammouse=2,
			shots=2,
			reltime=38,
			tohit=0.5,
			sound="machinegun",
			dmgtype="bullet",
			weaptype="rapid",
			pickupmsg="Peace through superior firepower!",
			desc="Everyone loves big guns that lay down a lot of lead. The \"Defender\" is just that.",
			char="}",
			color={0.12,0.12,0.3,1}
		},
		autoshotty = {
			type="weapon",
			name="Autoshotgun",
			dice=3,
			sides=4,
			maxammo=12,
			ammotype="12ga",
			atktime=4,
			reltime=38,
			tohit=0.7,
			range=6,
			sound="shotgun",
			dmgtype="spread",
			weaptype="rapid",
			pickupmsg="Mine eyes can but weep!",
			desc="What a lovely day! Truly an amazing invention, the AS-19 Autoshotgun is exactly what it says on the tin.",
			char="}",
			color={0.5,0.1,0.25,1}
		},
		supershotgun = {
			type="weapon",
			name="Supershotgun",
			dice=4,
			sides=5,
			maxammo=2,
			ammotype="12ga",
			atktime=4,
			ammouse=2,
			shots=2,
			reltime=12,
			tohit=0.8,
			range=4,
			sound="ssg",
			dmgtype="spread",
			weaptype="sidearm",
			pickupmsg="This doesn't seem remotely fair.",
			desc="Some kinda fuckin' supershotgun. No identifying marks. Something deeply empowering about the way it fits in my hands.",
			char="}",
			color={1.0,0.0,0.25,1}
		},
		ch9pis = {
			type="weapon",
			name="CH9 Pistol",
			dice=4,
			sides=5,
			maxammo=15,
			ammotype="9mm",
			atktime=12,
			ammouse=3,
			shots=3,
			reltime=18,
			tohit=0.85,
			sound="ch9",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="This is just a CH7 with a burstfire funswitch. Otherwise identical. Absolutely stellar gun.",
			char="}",
			color={0.1,0.3,0.2,1}
		},
		g26rifle = {
			type="weapon",
			name="G26 Rifle",
			dice=4,
			sides=5,
			maxammo=21,
			ammotype="5mm",
			atktime=7,
			ammouse=3,
			shots=3,
			reltime=20,
			tohit=0.566,
			sound="g11",
			dmgtype="bullet",
			weaptype="rapid",
			desc="A forgotten relic, the G26 is. It was a rechamber of another gun, chosen for its lightning fast burstfires.",
			char="}",
			color={0.4,0.4,0.15,1}
		},
		
		secarm = {
			type="armor",
			name="Security Armor",
			shortname="Sec Armor",
			maxdurability=60,
			protection=1,
			painfactor=0.9,
			movetime=1.0,
			desc="Lightweight security armor that will only really serve to stop small attacks. At least it lasts a while.",
			char="[",
			color={0.2,0.4,0.6,1}
		},
		riotarm = {
			type="armor",
			name="Riot Armor",
			shortname="Riot Armor",
			maxdurability=70,
			protection=2,
			painfactor=0.6,
			movetime=1.25,
			desc="A suit of riot armor that will stop a fair bit of those annoying bullets. It won't hold up long to any heavy fire.",
			char="[",
			color={0.7,0.7,0.7,1}
		},
		milarm = {
			type="armor",
			name="Militia Armor",
			shortname="Mil Armor",
			maxdurability=100,
			protection=3,
			painfactor=0.8,
			movetime=1.15,
			desc="Finally, some quality armor. Easy to move in hybrid armor that's likely to hold up to a lot of punishment.",
			char="[",
			color={0.2,0.6,0.2,1}
		},
		balarm = {
			type="armor",
			name="Ballistic Armor",
			shortname="Heavy Armor",
			maxdurability=150,
			protection=5,
			painfactor=0.4,
			movetime=1.6,
			pickupmsg="It's... REALLY heavy.",
			desc="This heavy ballistic armor is prepared for anything from a battle rifle round to a point-blank shotgun shell. Makes it rather hard to move, though...",
			char="[",
			color={0.1,0.2,0.1,1}
		},
		nrgarm = {
			type="armor",
			name="Energy Armor",
			shortname="En. Armor",
			maxdurability=170,
			protection=3,
			painfactor=0.4,
			movetime=1.0,
			pickupmsg="Glorious day it is!",
			desc="A chest mounted passive energy shield. Given Nuclear's track record, I don't think I wanna know what kind of radiation this'd pump into you... At least it'll last you ages.",
			char="[",
			color={0.6,0.4,0.9,1}
		},
	},
	
	clearenemytable = true,
	enemyspawntable = {
		{"pissecguard",1,3},	-- 1, 1, 1, 1
		{"secdog",6,2},			-- 3, 3, 2, 1
		{"shotsecguard",9,2},	-- 5, 3, 3, 2
		{"secdog",10,1},		-- 5, 4, 3, 2
		{"shotsecguard",11,1},	-- 5, 4, 3, 3
		{"smgtacguard",13,3},	-- 6, 4, 4, 3
		{"secdog",13,2},		-- 6, 4, 4, 3
		{"smgtacguard",16,2},	-- 7, 5, 5, 3
		{"rifletacguard",16,4},	-- 7, 5, 5, 3
		{"secdog",18,3},		-- 8, 6, 5, 4
		{"smgtacguard",20,3},	-- 9, 6, 5, 4
		{"rifletacguard",21,2},	-- 9, 6, 5, 4
		{"riflemilguard",28,5},	--12, 8, 7, 5
		{"mildog",28,3},		--12, 8, 7, 5
		{"mildog",31,4},		--13, 9, 7, 5
		{"shotmilguard",31,4},	--13, 9, 7, 5
		{"riflemilguard",32,2},	--13, 9, 7, 6
		{"shotmilguard",34,6},	--14, 9, 8, 6
		{"mildog",35,4},		--14, 9, 8, 6
		{"riflemilguard",35,4},	--14, 9, 8, 6
		{"shotmilguard",36,6},	--14,10, 8, 6
		{"riflemilguard",40,4}, --16,10, 9, 7
		{"shockdrone",42,5},	--16,11, 9, 7
		{"gundrone",45,4},		--17,11, 9, 7
		{"shockdrone",48,3},	--18,12,10, 7
		{"shotmilguard",50,6},	--19,12,10, 8
		{"gundrone",52,6},		--19,13,10, 8
		{"mildog",56,6},		--21,13,11, 8
		{"riflemilguard",60,8},	--22,14,12, 9
		{"shockdrone",64,5},	--23,15,12, 9
		{"gundrone",65,6},		--23,15,12, 9
	},
	
	clearitemtable = true,
	itemspawntable = {
		{"m99pis",-3,8,12,"w"},{"painkiller",-3,2,1},{"bandage",-3,2,1},
		{"painkiller",-1,2,1},{"secarm",-1,4,60,"a"},
		{"autopis",0,1,20,"w"},
		{"sawnoff",1,1,2,"w"},{"baton",1,1,0,"w"},{"bandage",2,2,1},
		{"sawnoff",2,5,2,"w"},{"machete",2,2,0,"w"},{"witchmag",2,4,6,"w"},{"medikit",2,1,1},{"bandage",2,2,1},
		{"sm40smg",3,3,30,"w"},{"sawnoff",3,1,2,"w"},{"secarm",3,3,60,"a"},{"riotarm",3,1,70,"a"},{"adrenaline",3,2,1},
		{"riotarm",4,5,70,"a"},{"machete",4,1,0,"w"},{"mk23pis",4,4,9,"w"},{"knuckles",4,1,0,"w"},{"bandage",4,2,1},{"medikit",4,3,1},
		{"sm40smg",5,4,30,"w"},{"riotarm",5,3,70,"a"},{"knuckles",5,2,0,"w"},{"huntrifle",5,3,10,"w"},{"ch7pis",5,4,15,"w"},
		{"mk23pis",6,2,9,"w"},{"huntrifle",6,4,10,"w"},{"traumakit",6,1,1},{"medikit",6,2,1},{"adrenaline",6,2,1},{"ca12shotty",6,3,6,"w"},{"milarm",6,2,100,"a"},
		{"riotarm",7,4,70,"a"},{"milarm",7,4,100,"a"},{"traumakit",7,4,1},{"combatstim",7,3,1},{"ca12shotty",7,5,6,"w"},
		{"sn730rifle",8,4,30,"w"},{"ch7pis",8,4,15,"w"},{"combatstim",8,2,1},{"traumakit",8,3,1},{"medikit",8,2,1},
		{"bossrifle",9,4,8,"w"},{"huntrifle",9,1,10,"w"},{"z3rifle",9,1,20,"w"},{"ch9pis",9,3,15,"w"},{"milarm",9,6,100,"a"},
		{"ca12shotty",10,5,6,"w"},{"sn730rifle",10,5,30,"w"},{"ch7pis",10,3,15,"w"},{"z3rifle",10,3,20,"w"},{"balarm",10,3,150,"a"},
		{"traumakit",11,2,1},{"medikit",11,1,1},{"adrenaline",11,2,1},{"combatstim",11,2,1},{"ch9pis",11,3,15,"w"},
		{"bossrifle",12,4,8,"w"},{"z3rifle",12,3,20,"w"},{"ca12shotty",12,5,6,"w"},
		{"z3rifle",13,4,20,"w"},{"balarm",13,5,150,"a"},{"nrgarm",13,4,170,"a"},
		{"nrgarm",14,4,170,"a"},{"magsmg",14,6,22,"w"},{"z3rifle",14,4,20,"w"},{"combatstim",14,4,1},{"traumakit",14,6,1},
		{"ch9pis",15,5,15,"w"},{"g26rifle",15,4,21,"w"},{"machinegun",15,3,50,"w"},
		{"autoshotty",16,5,12,"w"},{"supershotgun",16,4,2,"w"},{"nrgarm",16,5,170,"a"},{"magsmg",16,4,22,"w"},{"z3rifle",16,4,20,"w"},
		{"traumakit",17,7,1},{"balarm",17,6,150,"a"},{"ch9pis",17,5,15,"w"},{"supershotgun",17,5,2,"w"},
	},
	
	soundfx = {
		pistol = love.audio.newSource("sounds/pistol.wav","static"),
		ch9 = love.audio.newSource("sounds/ch9.wav","static"),
		magnum = love.audio.newSource("sounds/magnum.wav","static"),
		submachine = love.audio.newSource("sounds/submachine.wav","static"),
		sm41 = love.audio.newSource("sounds/sm41.wav","static"),
		rifle = love.audio.newSource("sounds/riflesmall.wav","static"),
		g11 = love.audio.newSource("sounds/g11.wav","static"),
		machinegun = love.audio.newSource("sounds/machinegun.wav","static"),
		batrifle = love.audio.newSource("sounds/rifle.wav","static"),
		shotgun = love.audio.newSource("sounds/batrifle.wav","static"),
		ssg = love.audio.newSource("sounds/supershotgun.wav","static"),
		melee = love.audio.newSource("sounds/pistol.wav","static"),
	},
	
	--the presetlevels block has information for any special levels that are to appear and at what floor and layer
	--if clearlevels is set to true then any already loaded preset levels will be removed, so only your mod's levels are loaded
	clearlevels = true,
	presetlevels = {
		{--4,1
			floor = 4,
			layer = 1,
			name = "Security Checkpoint",
			filename = "basea/levels/checkpoint.json",
			entrytext = "Entering the checkpoint. High security, what hospitality.",
			calmtext = "All is calm. But my documents were all in order!",
			music = love.audio.newSource("music/Meltdown.wav","stream"),
		},
		{--8,1
			floor = 8,
			layer = 1,
			name = "Waste Refinery Center",
			filename = "basea/levels/refinery.json",
			entrytext = "Entering the refinery. Do I have to go down there?",
			calmtext = "All is calm. Now I gotta go before my lungs collapse.",
			music = love.audio.newSource("music/LongWar.wav","stream"),
		},
		--[[{--8,2
			floor = 8,
			layer = 2,
			name = "Barricade",
			entrytext = "Some kind of barricade. It seems they were waiting for me.",
			calmtext = "All is calm. What a nightmare.",
			music = love.audio.newSource("music/LongWar.wav","stream"),
		},
		{--12,1
			floor = 12,
			layer = 1,
			name = "Medical Room",
			entrytext = "Entering the medical room. I sense a certain tension.",
			calmtext = "All is calm. The scent of viscera is overwhelming.",
			music = love.audio.newSource("music/LongWar.wav","stream"),
		},
		{--12,2
			floor = 12,
			layer = 2,
			name = "High Security Vault",
			entrytext = "Entering the vault. It's like a fortress down here.",
			calmtext = "All is calm. Now what kind of loot did you leave me?",
			music = love.audio.newSource("music/LongWar.wav","stream"),
		},
		{--12,3
			floor = 12,
			layer = 3,
			name = "Main Lab",
			entrytext = "Entering the main lab. What's that sound...? Uh oh.",
			calmtext = "All is calm. Now where can I lay down to die in peace?",
			music = love.audio.newSource("music/LongWar.wav","stream"),
		},]]--
	},
	
	enemyrate = 1.0,
	itemrate = 1.0,
	
	playerinventory = nil,
	playerammo = nil,
}