--return{ commented to break the mod so it doesn't load
	modinfo = "Because who doesn't love killing nazis?",
	
	items = {
		knife = {
			type="weapon",
			name="Knife",
			dice=3,
			sides=3,
			chrgtime=-4,
			chrgbonus={0,0,0},
			charge=1,
			ammotype="no",
			atktime=4,
			tohit=0.9,
			sound="melee",
			dmgtype="melee",
			weaptype="small",
			desc="How lucky that you managed to sneak this from a guard?",
			char="/",
			color={0.6,0.6,0.7,1}
		},
		m99pis = {
			type="weapon",
			name="Pistol",
			dice=2,
			sides=12,
			maxammo=8,
			ammotype="9mm",
			atktime=6,
			reltime=18,
			tohit=0.85,
			sound="pistol",
			dmgtype="bullet",
			weaptype="sidearm",
			desc="The nazi Walther P38. Stolen from a nazi guard. Time to kill some with it.",
			char="}",
			color={0.7,0.5,0.2,1}
		},
		sm40smg = {
			type="weapon",
			name="Machinegun",
			dice=2,
			sides=10,
			shots=3,
			ammouse=3,
			maxammo=32,
			ammotype="9mm",
			atktime=7,
			reltime=24,
			tohit=0.55,
			sound="submachine",
			dmgtype="bullet",
			weaptype="rapid",
			desc="This is an MP40. Standard and straightforward bullet hose. These ones are integrally suppressed.",
			char="}",
			color={0.65,0.65,0.7,1}
		},
		machinegun = {
			type="weapon",
			name="Gatling gun",
			dice=2,
			sides=10,
			shots=3,
			ammouse=3,
			maxammo=60,
			ammotype="9mm",
			atktime=3,
			reltime=24,
			tohit=0.45,
			sound="submachine",
			dmgtype="bullet",
			weaptype="rapid",
			desc="This is a gatling gun. It gatles. It's time to finally lay down some serious lead on these scumbags.",
			char="}",
			color={0.55,0.65,0.9,1}
		},
	},
	
	enemies = {
		pissecguard = {
			char="g",
			color={0.7,0.4,0.35,1},
			health=18,
			atksound="pistol",
			dice=2,
			sides=10,
			tohit=0.9,
			shots=1,
			xp=5,
			movetime=9,
			cooldown=1,
			aggro=0.6,
			range=8,
			name="Guard",
			desc="Regular low-ranking guard. Probably thinks he's one of the good guys. He's a nazi, what he thinks doesn't particularly matter to you.",
			deathmsg="The guard falls with a cartoonish scream.",
			ammo="9mm",ammocount=8,drops={"m99pis"}
		},
		smgtacguard = {
			char="S",
			color={0.1,0.1,0.9,1},
			health=50,
			atksound="submachine",
			dice=2,
			sides=8,
			tohit=0.7,
			shots=3,
			xp=15,
			movetime=9,
			cooldown=0,
			aggro=0.6,
			range=7,
			name="SS Guard",
			desc="An armored SS with a sick machinegun. Kill him and take it!",
			deathmsg="The SS stumbles to the ground.",
			ammo="9mm",ammocount=32,drops={"sm40smg","sm40smg","riotarm"}
		},
		rifletacguard = {
			char="o",
			color={0.7,0.7,0.7,1},
			health=26,
			atksound="pistol",
			dice=3,
			sides=8,
			tohit=1.0,
			shots=1,
			xp=10,
			movetime=6.5,
			cooldown=1,
			aggro=0.6,
			range=8,
			name="Officer",
			desc="An unfortunately uncowardly high ranking officer, well trained with his pistol.",
			deathmsg="The officer's body hits the floor.",
			ammo="9mm",ammocount=8,drops={"m99pis","secarm"}
		},
		riflemilguard = {
			char="M",
			color={0.0,0.45,0.0,1},
			health=24,
			atksound="pistol",
			dice=2,
			sides=8,
			tohit=0.7,
			shots=2,
			xp=12,
			movetime=8,
			cooldown=1,
			aggro=0.8,
			range=8,
			name="Mutant",
			desc="The fuck even is this thing? Some kind of nazi zombie!",
			deathmsg="The mutant dies with a groan.",
			ammo="9mm",ammocount=8,drops={"m99pis"}
		},
		secdog = {
			char="s",
			color={0.6,0.3,0.2,1},
			health=2,
			dice=2,
			sides=4,
			tohit=0.8,
			shots=2,
			xp=2,
			movetime=6,
			cooldown=1,
			aggro=1,
			range=1,
			name="Dog",
			desc="\"Fuck these nazis, and fuck their dogs, who are not good boys, and do not go to doggy heaven!\"",
			deathmsg="The dog falls to its side."
		},
	},
	
	playerinventory = {
		"m99pis"
	},
	playerammo = {8,0,0,0,0},
	
	presetlevels = {
		{ --w1f1
			floor = 1,
			name = "Floor 1",
			filename = "Nuclenstein_3D/w1f1.json",
			entrytext = "The guard is dead. His pistol is yours. There's no going back now.",
			calmtext = "All is calm. The elevator is waiting.",
			music = love.audio.newSource("music/Meltdown.wav","stream"),
		},
	},
}